// Code generated by "stringer -type=conditionType"; DO NOT EDIT.

package yql_elastic

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[queryShould-0]
	_ = x[queryMust-1]
	_ = x[queryMustNot-2]
}

const _conditionType_name = "queryShouldqueryMustqueryMustNot"

var _conditionType_index = [...]uint8{0, 11, 20, 32}

func (i conditionType) String() string {
	if i < 0 || i >= conditionType(len(_conditionType_index)-1) {
		return "conditionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _conditionType_name[_conditionType_index[i]:_conditionType_index[i+1]]
}
