// Code generated by "stringer -type=matchType"; DO NOT EDIT.

package yql_elastic

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[autoMatch-0]
	_ = x[phraseMatch-1]
	_ = x[keywordMatch-2]
	_ = x[regexMatch-3]
	_ = x[lowerMatch-4]
	_ = x[upperMatch-5]
}

const _matchType_name = "autoMatchphraseMatchkeywordMatchregexMatchlowerMatchupperMatch"

var _matchType_index = [...]uint8{0, 9, 20, 32, 42, 52, 62}

func (i matchType) String() string {
	if i < 0 || i >= matchType(len(_matchType_index)-1) {
		return "matchType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _matchType_name[_matchType_index[i]:_matchType_index[i+1]]
}
